laab7/Lab7/Lab7/Controllers/BSTUController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab7.Controllers
{
    public class BSTUController : Controller
    {
        // GET: BSTU
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.IsAuth = this.HttpContext.User.Identity.IsAuthenticated;
            ViewBag.UserName = this.HttpContext.User.Identity.Name;
            ViewBag.IsAdmin = this.HttpContext.User.IsInRole("Administrator");
            ViewBag.IsEmployer = this.HttpContext.User.IsInRole("Employer");

            return View();
        }

        [Authorize(Roles ="Administrator")]
        public ActionResult Config()
        {
            return View();
        }
    }
}

laab7/Lab7/Lab7/Controllers/FITController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab7.Controllers
{
    public class FITController : Controller
    {
        // GET: FIT
        [Authorize(Roles ="Guest,Employer")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIT_IS()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIT_PI()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIT_ID()
        {
            return View();
        }
    }
}

laab7/Lab7/Lab7/Views/FIT/FIT_ID.cshtml
@{
    ViewBag.Title = "FIT_ID";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FIT_ID</title>
</head>
<body>
    <h1>FIT_ID</h1>
    <table>
        <tr>
            <td>Авторизация выполнена? </td>
            <td>@(User.Identity.IsAuthenticated? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь </td>
            <td>@(!String.IsNullOrEmpty(User.Identity.Name) ? User.Identity.Name : "--" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Administrator?  </td>
            <td>@(User.IsInRole("Administrator")? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Employer? </td>
            <td>@(User.IsInRole("Employer") ? "да":"нет" )</td>
        </tr>
    </table>

    <div>
        @Html.ActionLink("FIT/Index", "/Index", "FIT")<br />

    </div>
</body>
</html>

laab7/Lab7/Lab7/Views/FIT/FIT_IS.cshtml
@{
    ViewBag.Title = "FIT_IS";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FIT_IS</title>
</head>
<body>
    <h1>FIT_IS</h1>
    <table>
        <tr>
            <td>Авторизация выполнена? </td>
            <td>@(User.Identity.IsAuthenticated? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь </td>
            <td>@(!String.IsNullOrEmpty(User.Identity.Name) ? User.Identity.Name : "--" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Administrator?  </td>
            <td>@(User.IsInRole("Administrator")? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Employer? </td>
            <td>@(User.IsInRole("Employer") ? "да":"нет" )</td>
        </tr>
    </table>

    <div>
        @Html.ActionLink("FIT/Index", "/Index", "FIT")<br />

    </div>
</body>
</html>

laab7/Lab7/Lab7/Views/FIT/FIT_PI.cshtml
@{
    ViewBag.Title = "FIT_PI";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FIT_PI</title>
</head>
<body>
    <h1>FIT_PI</h1>
    <table>
        <tr>
            <td>Авторизация выполнена? </td>
            <td>@(User.Identity.IsAuthenticated? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь </td>
            <td>@(!String.IsNullOrEmpty(User.Identity.Name) ? User.Identity.Name : "--" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Administrator?  </td>
            <td>@(User.IsInRole("Administrator")? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Employer? </td>
            <td>@(User.IsInRole("Employer") ? "да":"нет" )</td>
        </tr>
    </table>

    <div>
        @Html.ActionLink("FIT/Index", "/Index", "FIT")<br />

    </div>
</body>
</html>

laab7/Lab7/Lab7/Views/FIT/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h1>FIT</h1>
    <table>
        <tr>
            <td>Авторизация выполнена? </td>
            <td>@(User.Identity.IsAuthenticated? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь </td>
            <td>@(!String.IsNullOrEmpty(User.Identity.Name) ? User.Identity.Name : "--" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Administrator?  </td>
            <td>@(User.IsInRole("Administrator")? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Employer? </td>
            <td>@(User.IsInRole("Employer") ? "да":"нет" )</td>
        </tr>
    </table>

    <div>
        @if (User.IsInRole("Employer")|| User.IsInRole("Guest"))
        {
            @Html.ActionLink("FIT/FIT_IS", "/FIT_IS", "FIT")<br />
            @Html.ActionLink("FIT/FIT_PI", "/FIT_PI", "FIT")<br />
            @Html.ActionLink("FIT/FIT_ID", "/FIT_ID", "FIT")<br />
        }
        @Html.ActionLink("BSTU/Index", "/Index", "BSTU")<br />

    </div>
</body>
</html>