lab3/lab3/lab3/Models/PhoneBookRepository/PhoneBookRepostiroy.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

namespace lab3.Models.PhoneBookRepository
{
    public class PhoneBookRepostiroy
    {
        private string path;
        private string json;
        private List<PhoneNote> phoneNoteList;

        public PhoneBookRepostiroy()
        {
            path = AppDomain.CurrentDomain.BaseDirectory + @"\App_Data\PhoneBook.json";
            Console.WriteLine(path);
            json = File.ReadAllText(path);
            phoneNoteList = JsonConvert.DeserializeObject<List<PhoneNote>>(json) ?? new List<PhoneNote>();
        }

        public PhoneNote Create(PhoneNote phonebookRecord)
        {
            phoneNoteList.Sort((r1, r2) => r1.Id - r2.Id);
            var lastRecord = phoneNoteList.FindLast(r => true);
            if (lastRecord != null)
                phonebookRecord.Id = lastRecord.Id + 1;
            phoneNoteList.Add(phonebookRecord);
            File.WriteAllText(path, JsonConvert.SerializeObject(phoneNoteList));
            return phonebookRecord;
        }
        public PhoneNote Delete(int id)
        {
            var phonebookRecord = phoneNoteList.Find(r => r.Id == id);
            phoneNoteList.Remove(phonebookRecord);
            File.WriteAllText(path, JsonConvert.SerializeObject(phoneNoteList));
            return phonebookRecord;
        }
        public PhoneNote Edit(PhoneNote phonebookRecord)
        {
            var index = phoneNoteList.FindIndex(r => r.Id == phonebookRecord.Id);
            phoneNoteList[index] = phonebookRecord;
            File.WriteAllText(path, JsonConvert.SerializeObject(phoneNoteList));
            return phonebookRecord;
        }

        public PhoneNote Find(int id)
        {
            return phoneNoteList.Find(r => r.Id == id);
        }

        public IEnumerable<PhoneNote> List()
        {
            return phoneNoteList.OrderBy(x => x.Name);
        }
    }
}

lab3/lab3/lab3/Models/PhoneNote.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace lab3.Models
{
    public class PhoneNote
    {
        // ID записи
        public int Id { get; set; }
        // ФИО 
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Длина имени должна быть больше 3 и меньше 50")]
        public string Name { get; set; }
        // Телефон
        [RegularExpression(@"^\+\d{12}$", ErrorMessage = "Неверный формат телефона")]
        public string PhoneNumber { get; set; }
    }
}

lab3/lab3/lab3/Controllers/DictController.cs
using lab3.Models;
using lab3.Models.PhoneBookRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace lab3.Controllers
{
    public class DictController : Controller
    {
        private PhoneBookRepostiroy db = new PhoneBookRepostiroy();
        // GET: Dict
        public ActionResult Index()
        {
            return View(db.List());
        }

        // GET: Dict/Create
        public ActionResult Add()
        {
            return View();
        }

        // POST: Dict/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "Id,Name,PhoneNumber")] PhoneNote phonebookRecord)
        {
            if (ModelState.IsValid)
            {
                db.Create(phonebookRecord);
                return RedirectToAction("Index");
            }

            return View(phonebookRecord);
        }

        // GET: Dict/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhoneNote phonebookRecord = db.Find(id.Value);
            if (phonebookRecord == null)
            {
                return HttpNotFound();
            }
            return View(phonebookRecord);
        }

        // POST: Dict/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,PhoneNumber")] PhoneNote phonebookRecord)
        {
            if (ModelState.IsValid)
            {
                db.Edit(phonebookRecord);
                return RedirectToAction("Index");
            }
            return View(phonebookRecord);
        }

        // GET: Dict/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhoneNote phonebookRecord = db.Find(id.Value);
            if (phonebookRecord == null)
            {
                return HttpNotFound();
            }
            return View(phonebookRecord);
        }

        // POST: Dict/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

lab3/lab3/lab3/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab3.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Error()
        {
            Response.StatusCode = 404;
            ViewBag.url = Request.Url.ToString().Split(';')[1];
            ViewBag.method = Request.HttpMethod;
            return View();
        }
    }
}

lab3/lab3/lab3/Views/Dict/Add.cshtml
@model lab3.Models.PhoneNote

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        <h4>Phone</h4>
        <hr />
        @Html.ValidationSummary()
        <div>
            @Html.LabelFor(model => model.Name)
            <div>
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name, "")
            </div>
        </div>

        <div>
            @Html.LabelFor(model => model.PhoneNumber)
            <div>
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber, "")
            </div>
        </div>

        <div>
            <div>
                <input type="submit" value="Add" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

lab3/lab3/lab3/Views/Dict/Delete.cshtml
@model lab3.Models.PhoneNote

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Phone Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

lab3/lab3/lab3/Views/Dict/Edit.cshtml
@model lab3.Models.PhoneNote

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Phone Note</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

lab3/lab3/lab3/Views/Dict/Index.cshtml
@model IEnumerable<lab3.Models.PhoneNote>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Add")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

lab3/lab3/lab3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Dict", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Error страница", "Index", "sd")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>