laab7/Lab7/Lab7/Controllers/BSTUController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab7.Controllers
{
    public class BSTUController : Controller
    {
        // GET: BSTU
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.IsAuth = this.HttpContext.User.Identity.IsAuthenticated;
            ViewBag.UserName = this.HttpContext.User.Identity.Name;
            ViewBag.IsAdmin = this.HttpContext.User.IsInRole("Administrator");
            ViewBag.IsEmployer = this.HttpContext.User.IsInRole("Employer");

            return View();
        }

        [Authorize(Roles ="Administrator")]
        public ActionResult Config()
        {
            return View();
        }
    }
}

laab7/Lab7/Lab7/Controllers/FIEController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab7.Controllers
{
    public class FIEController : Controller
    {
        // GET: FIE
        [Authorize(Roles = "Guest,Employer")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIE_TM()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIE_UR()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIE_UP()
        {
            return View();
        }
    }
}

laab7/Lab7/Lab7/Views/FIE/FIE_TM.cshtml
@{
    ViewBag.Title = "FIE_TM";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FIE_TM</title>
</head>
<body>
    <h1>FIE_TM</h1>
    <table>
        <tr>
            <td>Авторизация выполнена? </td>
            <td>@(User.Identity.IsAuthenticated? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь </td>
            <td>@(!String.IsNullOrEmpty(User.Identity.Name) ? User.Identity.Name : "--" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Administrator?  </td>
            <td>@(User.IsInRole("Administrator")? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Employer? </td>
            <td>@(User.IsInRole("Employer") ? "да":"нет" )</td>
        </tr>
    </table>

    <div>
        @Html.ActionLink("FIT/Index", "/Index", "FIE")<br />

    </div>
</body>
</html>

laab7/Lab7/Lab7/Views/FIE/FIE_UP.cshtml
@{
    ViewBag.Title = "FIE_UP";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FIE_UP</title>
</head>
<body>
    <h1>FIE_UP</h1>
    <table>
        <tr>
            <td>Авторизация выполнена? </td>
            <td>@(User.Identity.IsAuthenticated? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь </td>
            <td>@(!String.IsNullOrEmpty(User.Identity.Name) ? User.Identity.Name : "--" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Administrator?  </td>
            <td>@(User.IsInRole("Administrator")? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Employer? </td>
            <td>@(User.IsInRole("Employer") ? "да":"нет" )</td>
        </tr>
    </table>

    <div>
        @Html.ActionLink("FIE/Index", "/Index", "FIE")<br />

    </div>
</body>
</html>

laab7/Lab7/Lab7/Views/FIE/FIE_UR.cshtml
@{
    ViewBag.Title = "FIE_UR";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FIE_UR</title>
</head>
<body>
    <h1>FIE_UR</h1>
    <table>
        <tr>
            <td>Авторизация выполнена? </td>
            <td>@(User.Identity.IsAuthenticated? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь </td>
            <td>@(!String.IsNullOrEmpty(User.Identity.Name) ? User.Identity.Name : "--" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Administrator?  </td>
            <td>@(User.IsInRole("Administrator")? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Employer? </td>
            <td>@(User.IsInRole("Employer") ? "да":"нет" )</td>
        </tr>
    </table>

    <div>
        @Html.ActionLink("FIE/Index", "/Index", "FIE")<br />

    </div>
</body>
</html>

laab7/Lab7/Lab7/Views/FIE/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h1>FIE</h1>
    <table>
        <tr>
            <td>Авторизация выполнена? </td>
            <td>@(User.Identity.IsAuthenticated? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь </td>
            <td>@(!String.IsNullOrEmpty(User.Identity.Name) ? User.Identity.Name : "--" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Administrator?  </td>
            <td>@(User.IsInRole("Administrator")? "да":"нет" )</td>
        </tr>
        <tr>
            <td>Текущий пользователь имеет роль Employer? </td>
            <td>@(User.IsInRole("Employer") ? "да":"нет" )</td>
        </tr>
    </table>

    <div>
        @if (User.IsInRole("Employer") || User.IsInRole("Guest"))
        {
            @Html.ActionLink("FIE/FIE_TM", "/FIE_TM", "FIE")<br />
            @Html.ActionLink("FIE/FIE_UR", "/FIE_UR", "FIE")<br />
            @Html.ActionLink("FIE/FIE_UP", "/FIE_UP", "FIE")<br />
        }
        @Html.ActionLink("BSTU/Index", "/Index", "BSTU")<br />

    </div>
</body>
</html>